name: Simulate Success for Release PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited

permissions:
  id-token: write
  contents: read
  statuses: write

jobs:
  release_chore:
    if: "startsWith(github.event.pull_request.title, 'chore(main): release')"
    runs-on: ubuntu-latest
    steps:
      - name: Post success status for release chore.
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: "Lint Test / lint_test"
          description: "Passed"
          state: "success"
          sha: ${{github.event.pull_request.head.sha || github.sha}}
